version: '3.8'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: rapid_vax  # Nom de la base de données
      MYSQL_USER: user           # Nom d'utilisateur
      MYSQL_PASSWORD: password   # Mot de passe
      MYSQL_ROOT_PASSWORD: rootpassword # Mot de passe de l'utilisateur root
    ports:
      - "3306:3306"              # Mappage des ports
    volumes:
      - mysql_data:/var/lib/mysql   # Volume pour la persistance des données
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # script d'initialisation

volumes:
  mysql_data:
